{"name": "test_xfail_unexpected_pass", "status": "passed", "statusDetails": {"message": "XPASS this test is expecting failure"}, "description": "this test is an xfail that will be marked as unexpected success", "start": 1588906491714, "stop": 1588906491714, "uuid": "58a43cee-af3f-4006-b27e-782a3657d3de", "historyId": "bd8fdb7f3ba00d399bc242a88f81b9ad", "testCaseId": "bd1ce0e0c00c48bf56abc92f9a63f929", "fullName": "test_failure#test_xfail_unexpected_pass", "labels": [{"name": "suite", "value": "test_failure"}, {"name": "host", "value": "pinrongdeMacBook-Pro.local"}, {"name": "thread", "value": "90385-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_failure"}]}